/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    'Post-': typeof import('./components/Post-.vue')['default']
    PostForm: typeof import('./components/PostForm.vue')['default']
    PostFrom: typeof import('./components/PostFrom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TipTapEditor: typeof import('./components/TipTapEditor.vue')['default']
    VQuillField: typeof import('./components/VQuillField.vue')['default']
  }
}
